### PR TITLE
Add statement on explicitly returning nothing in control functions

### PR DESCRIPTION
**Pull request by BSchilperoort**
Ref https://github.com/csdms/bmi-example-julia/issues/8

I added a general statement in the initialize docstring to avoid too much repetition.

### CODE REVIEW

**Comment by BSchilperoort** [comment]
Working on the implementation in csdms/bmi-example-julia, I realize that `initialize` needs to return the model. I could have also looked at #1 of course.

**Comment by visr** [comment]
Ha interesting that you chose `initialize`, since that is the odd one out in this case I believe, see #1 (which I now see you just found). Perhaps we could document that if a type is passed, we return the model, but if a model is passed, we return nothing.

I think I'd prefer the repetition in this case though, since I don't think we can necessarily expect everyone to read the `initialize` docstring first.

**Comment by BSchilperoort** [comment]
> Perhaps we could document that if a type is passed, we return the model, but if a model is passed, we return nothing.

I think consistency would be best here, i.e. always return the model.

In what case would you already have the model instantiated, and would want to re-use the struct to initialize it again? I'm having a hard time picturing that.

**Comment by visr** [comment]
> always return the model

Yes that's also fine by me.

> In what case would you already have the model instantiated, and would want to re-use the struct to initialize it again? 

Yeah I was thinking of some constructor that has empty arrays, which are then filled with initialize or something like that. But I don't really think it is needed, and I see bmi-example-julia, Wflow and Ribasim all only have the method on the type and not the instance. So perhaps a better way to resolve #1 would be to document that this is the only way: `BMI.initialize(::Type{MyModel}, config_file)::MyModel`.

**Comment by BSchilperoort** [comment]
> would be to document that this is the only way: `BMI.initialize(::Type{MyModel}, config_file)::MyModel`

To add these types, I'd have to define a MyModel struct. Shall I do that and also add types elsewhere?

**Comment by visr** [comment]
Ah I meant to only document this. The MyModel struct example is not for BMI.jl but for users of BMI.jl.

**Comment by BSchilperoort** [comment]
@visr I've added an example implementation to initialize that should hopefully clear up any confusion.

**Comment by BSchilperoort** [comment]
I do see that in Wflow.jl and Ribasim you don't actually use the model's type, and that it's only passed so that julia uses the correct function. Maybe it's good to actually clarify that.

**Comment by visr** [comment]
@BSchilperoort sorry for pushing large changes to your branch, but I figured we might as well document all return types and argument types. I added them in d2e4f65b732ac8b592f3c469f250c164c825904e. Do you agree with these?

Keeping https://github.com/csdms/bmi-example-julia/issues/8#issuecomment-2468324560 in mind, I went for e.g. DenseVector return types for cross language interoperability. AbstractVector would be more logical if it was just for Julia.

There are two things that I am wondering. For e.g. this signature:

```julia
get_grid_node_count(model, grid::Int)::Int
```

Should the grid and return count both maybe be Int rather than Int32? Normally Julia functions like `length` and `size` return Int, but SIDL/C/C++ states `int`, which is more likely to be a `Int32`. The same goes for the connectivity vectors:

```julia
get_grid_edge_nodes(model, grid::Int, edge_nodes::DenseVector{Int})::DenseVector{Int}
```

Here it is probably even more important that the integer size matches what is expected in other languages. So do you think I should change all Int to Int32 in BMI functions? If so we should probably update implementations.

**Comment by BSchilperoort** [comment]
Thanks for picking this up, Martijn!

> I figured we might as well document all return types and argument types.

That's great, I think that will help reduce ambiguity a lot.

> DenseVector return types for cross language interoperability. AbstractVector would be more logical if it was just for Julia.

I don't know enough about Julia to comment on this. The Julia docs also don't really help here :/

> Should the grid and return count both maybe be Int rather than Int32? Normally Julia functions like `length` and `size` return Int, but SIDL/C/C++ states `int`, which is more likely to be a `Int32`. The same goes for the connectivity vectors:

I feel like just "Int" is fine. If someone wants to do cross-language stuff this shouldn't be a big problem. It will basically always be a 64-bit integer as 32-bit is largely being phased out.

For example, Python 3 does not have a native 32-bit integer type; it's int type is 64 bits. Numpy does support smaller integers though.

However, we generally use protocols such as gRPC or a RESTful API to couple models, so I am not sure if this is different for very tightly coupled models where you're also sharing pointers.

You could ask this in a post on https://forum.csdms.io/, the new CSDMS discussion forum.

**Comment by visr** [comment]
> I feel like just "Int" is fine. If someone wants to do cross-language stuff this shouldn't be a big problem. It will basically always be a 64-bit integer as 32-bit is largely being phased out.

Ok, I'll keep it as is for now. I agree about scalar Int, for arrays the interoperability can be more difficult if one side expects Int32 and the other Int64.

> For example, Python 3 does not have a native 32-bit integer type; it's int type is 64 bits.

Actually Python's int is unlimited precision, but that's another discussion :)

> You could ask this in a post on https://forum.csdms.io/, the new CSDMS discussion forum.

Good to know, thanks, I've signed up. For now I'll go ahead and merge this.

**Review by visr — APPROVED** [review]

**Pull request merged**
